services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception_network
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    environment:
      - HTTP_HOST=${DOMAIN_NAME}
      - WP_DB_HOST=${WP_DB_HOST}
      - WP_DB_NAME=${MYSQL_DATABASE}
      - WP_DB_USER=${MYSQL_USER}
      - WP_DB_PASSWORD=${MYSQL_PASSWORD}
      - WP_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - WP_SITE_NAME=${WP_SITE_NAME}
      - WP_ADMIN_USERNAME=${WP_ADMIN_USERNAME}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_SIMPLE_USERNAME=${WP_SIMPLE_USERNAME}
      - WP_SIMPLE_EMAIL=${WP_SIMPLE_EMAIL}
      - WP_SIMPLE_ROLE=${WP_SIMPLE_ROLE}
      - WP_SIMPLE_PASSWORD=${WP_SIMPLE_PASSWORD}
      - WP_DUMMY_XML=${WP_DUMMY_XML}
    depends_on:
      - mariadb
      - redis
    networks:
      - inception_network
    volumes:
      - wp_data:/var/www/html:rw
    expose:
      - 9000
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    environment:
      - CERTS_=${CERTS_}
    expose:
      - 443
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - django
    networks:
      - inception_network
    volumes:
      - wp_data:/usr/share/nginx/html
    restart: always

  redis:
    build: ./requirements/redis
    image: redis
    container_name: redis
    networks:
      - inception_network
    expose:
      - 6379
    restart: always
  
  pure-ftpd:
    build: ./requirements/pure-ftpd
    image: pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - wp_data:/var/lib/ftp
    restart: always

  adminer:
    build: ./requirements/adminer
    image: adminer
    container_name: adminer
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 90001
    networks:
      - inception_network
    restart: always

  django:
    build: ./requirements/django
    image: django
    container_name: django
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    expose:
      - 8000
    networks:
      - inception_network
    restart: always

  kuma:
    build: ./requirements/kuma
    image: kuma
    container_name: kuma
    ports:
      - "3001:3001"
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /home/vshchuki/data/wp_data
      device: /Users/vshchuki/data/wp_data

  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      # device:  /home/vshchuki/data/db_data
      device:  /Users/vshchuki/data/db_data