services:
  mariadb:
    build: ./srcs/requirements/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception_network
    volumes:
      - db_data:/var/lib/mysql
      # - /Users/vshchuki/data/db_data:/var/lib/mysql
      # - /Users/mcp/Documents/data/db_data:/var/lib/mysql
      # - ./volumes/db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 3306
    restart: always

  nginx:
    build: ./srcs/requirements/nginx
    image: nginx
    container_name: nginx
    environment:
      - CERTS_=${CERTS_}
    expose:
      - 443
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - wp_data:/usr/share/nginx/html
      # - /Users/vshchuki/data/wp_data:/usr/share/nginx/html
      # - /Users/mcp/Documents/data/wp_data:/usr/share/nginx/html
      # - ./volumes/wp_data:/usr/share/nginx/html
    restart: always


  wordpress:
    build: ./srcs/requirements/wordpress
    image: wordpress
    container_name: wordpress
    environment:
      - HTTP_HOST=${DOMAIN_NAME}
      - WP_DB_HOST=${WP_DB_HOST}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_PASSWORD=${WP_DB_PASSWORD}
      - WP_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - WP_SITE_NAME=${WP_SITE_NAME}
      - WP_ADMIN_USERNAME=${WP_ADMIN_USERNAME}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_SIMPLE_USERNAME=${WP_SIMPLE_USERNAME}
      - WP_SIMPLE_EMAIL=${WP_SIMPLE_EMAIL}
      - WP_SIMPLE_ROLE=${WP_SIMPLE_ROLE}
      - WP_SIMPLE_PASSWORD=${WP_SIMPLE_PASSWORD}
      - WP_DUMMY_XML=${WP_DUMMY_XML}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception_network
    volumes:
      - wp_data:/var/www/html
      # - /Users/vshchuki/data/wp_data:/var/www/html
      # - /Users/mcp/Documents/data/wp_data:/var/www/html
      # - ./volumes/wp_data:/var/www/html
    expose:
      - 9000
    restart: always

networks:
  inception_network:
    name: inception_network
    driver: bridge

# volumes:
#   wp_data:
#     name: wp_data

#   db_data:
#     name: db_data

volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: ~/Documents/data/wp_data  # Specify host directory for WordPress data
      # device: ./volumes/wp_data1  # Specify host directory for WordPress data
      # device: /Users/mcp/Documents/tutorials-training/hive/projects/inception/volumes/wp_data1  # Specify host directory for WordPress data
      # device: /Users/mcp/Documents/tutorials-training/hive/projects/volumes/wp_data1  # Specify host directory for WordPress data
      # device: /Users/mcp/Documents/data/wp_data
      device: /Users/vshchuki/data/wp_data  # 

  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: ~/Documents/data/db_data1  # Specify host directory for MariaDB data
      # device: ./volumes/db_data1  # Specify host directory for MariaDB data
      # device: /Users/mcp/Documents/tutorials-training/hive/projects/inception/volumes/db_data1  # Specify host directory for MariaDB data
      # device: /Users/mcp/Documents/tutorials-training/hive/projects/volumes/db_data1  # Specify host directory for MariaDB data
      # device: /Users/mcp/Documents/data/db_data
      device:  /Users/vshchuki/data/db_data  # 