services:
  mariadb:
    build: ./srcs/requirements/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception_network
    volumes:
      - ./volumes/db_data:/var/lib/mysql
    expose:
      - 3306
    restart: always

  wordpress:
    build: ./srcs/requirements/wordpress
    image: wordpress
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - HTTP_HOST=${DOMAIN_NAME}
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - ./volumes/wp_data:/var/www/html
    expose:
      - 9000
    # ports:
    #   - "9000:80"  # Expose container port 80 to host port 9000
    restart: always

# volumes:
#   wp_data:
#   db_data:

networks:
  inception_network:
    name: inception_network
    driver: bridge