services:
  mariadb:
    build: ./srcs/requirements/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception_network
    volumes:
      - ./volumes/db_data:/var/lib/mysql
    expose:
      - 3306
    restart: always

  wordpress:
    build: ./srcs/requirements/wordpress
    image: wordpress
    container_name: wordpress
    environment:
      - HTTP_HOST=${DOMAIN_NAME}
      - WP_DB_HOST=${WP_DB_HOST}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_PASSWORD=${WP_DB_PASSWORD}
      - WP_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - WP_SITE_NAME=${WP_SITE_NAME}
      - WP_ADMIN_USERNAME=${WP_ADMIN_USERNAME}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_SIMPLE_USERNAME=${WP_SIMPLE_USERNAME}
      - WP_SIMPLE_EMAIL=${WP_SIMPLE_EMAIL}
      - WP_SIMPLE_ROLE=${WP_SIMPLE_ROLE}
      - WP_SIMPLE_PASSWORD=${WP_SIMPLE_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - ./volumes/wp_data:/var/www/html
    expose:
      - 9000
    # ports:
    #   - "9000:80"  # Expose container port 80 to host port 9000
    restart: always
  # nginx:
  #   build: ./srcs/requirements/nginx
  #   expose:
  #     - 443
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - mariadb
  #     - wordpress
  #   networks:
  #     - inception_network
  #   restart: always

  # volumes:
  #   wp_data:
  #   db_data:

networks:
  inception_network:
    name: inception_network
    driver: bridge
